name: saas-system-v1
services:
  db:
    image: postgres:latest
    container_name: saas-postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - saas-network

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: saas-backend-api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    networks:
      - saas-network

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: saas-frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - saas-network

volumes:
  postgres_data:

networks:
  saas-network:
    driver: bridge
